#!/bin/bash

################################################################################################################################################################

# @project        Open Space Toolkit ▸ Physics
# @file           binder/postBuild
# @author         Lucas Brémond <lucas@loftorbital.com>
# @license        Apache License 2.0

################################################################################################################################################################

# Install Jupyter widgets extension

jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1 --no-build

# Install Matplotlib for JupyterLab

jupyter labextension install jupyter-matplotlib --no-build

# Install Plotly for JupyterLab

## FigureWidget support

jupyter labextension install plotlywidget@1.4.0 --no-build

## JupyterLab renderer support

jupyter labextension install jupyterlab-plotly@1.4.0 --no-build

## Build extensions (must be done to activate extensions since --no-build is used above)

jupyter lab build

# Install Open Space Toolkit default datasets

mkdir -p /home/jovyan/open-space-toolkit/physics
gsutil -m cp -r gs://open-space-toolkit/physics /home/jovyan/open-space-toolkit/

################################################################################################################################################################
