#!/bin/bash

################################################################################################################################################################

# @project        Open Space Toolkit ▸ Physics
# @file           binder/postBuild
# @author         Lucas Brémond <lucas@loftorbital.com>
# @license        Apache License 2.0

################################################################################################################################################################

jupyter labextension install @jupyterlab/plotly-extension

wget --quiet https://github.com/open-space-collective/open-space-toolkit-physics/archive/master.zip

unzip -q master.zip

mkdir -p /open-space-toolkit

mv open-space-toolkit-physics-master/share /open-space-toolkit/physics

rm master.zip
rm -rf open-space-toolkit-physics-master

################################################################################################################################################################
